import React from "react";
import { Card } from "antd";
import {RegisterPackageForm} from "../components/forms/RegisterPackageForm";
import { usePackages } from "../hooks/services/usePackages";

/*
package = {
  id: -> generated by backend,
  origin: {
    street: "Main St",
    zipCode: "12345",
    city: "Buenos Aires",
    province: "Buenos Aires",
    country: "Argentina",
    address: "123 Main St, Apt 4",
    apartment: "4" -> optional
  },
  destination: {
    street: "Second St",
    zipCode: "67890",
    city: "Córdoba",
    province: "Córdoba",
    country: "Argentina",
    address: "456 Second St",
    apartment: "" ->  optional
  },
  state: "pending" | "in-transit" | "delivered" -> generated by backend,
  sender: "Alice",
  receiver: "Bob"
}
*/


export default function RegisterPackage() {
    const { packages, handleNewPackage } = usePackages();

    return (
        <div style={{ padding: "2rem" }}>
            <Card title="Register a New Package" style={{ maxWidth: 700, margin: "0 auto" }}>
                <RegisterPackageForm onSubmit={handleNewPackage} />
            </Card>

            {packages && packages.length > 0 && (
                <Card
                    title="Packages Added"
                    style={{ maxWidth: 700, margin: "2rem auto 0 auto" }}
                >
                    <ul>
                        {packages.map((pkg) => (
                            <li key={pkg.id}>
                                <strong>{pkg.id}</strong>: {pkg.origin} → {pkg.destination}, State:{" "}
                                {pkg.state}, Sender: {pkg.sender}, Receiver: {pkg.receiver}
                            </li>
                        ))}
                    </ul>
                </Card>
            )}
        </div>
    );
}
